In [2]:
import numpy as np

# Creating arrays
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("OUTPUT IS")
print("ONE DIMENSIONAL ARRAY IS:\n", a)

b = np.array([[10, 20], [40, 50]])
print("TWO DIMENSIONAL ARRAY IS:\n", b)

c = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("THREE DIMENSIONAL ARRAY IS:\n", c)


OUTPUT IS
ONE DIMENSIONAL ARRAY IS:
 [ 1  2  3  4  5  6  7  8  9 10]
TWO DIMENSIONAL ARRAY IS:
 [[10 20]
 [40 50]]
THREE DIMENSIONAL ARRAY IS:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [3]:
# Array indexing and attributes
x1 = np.array([45, 89, 64, 33])
x2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nArray indexing and numpy array attributes")
print("x1:", x1)
print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size:", x2.size)


Array indexing and numpy array attributes
x1: [45 89 64 33]
x2 ndim: 2
x2 shape: (3, 3)
x2 size: 9


In [4]:
# Accessing single elements
print("\nAccessing single elements")
print("Element at index -2 in x1:", x1[-2])
print("x2 before modification:\n", x2)
x2[1, 2] = 60
print("x2 after modification:\n", x2)


Accessing single elements
Element at index -2 in x1: 64
x2 before modification:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
x2 after modification:
 [[ 1  2  3]
 [ 4  5 60]
 [ 7  8  9]]


In [5]:
# Array slicing
print("\nArray slicing")
x = np.arange(10)
print("x[5:9]:", x[5:9])
print("x[:5]:", x[:5])
print("x[1::3]:", x[1::3])
print("x2[0:2, 0:2]:\n", x2[0:2, 0:2])


Array slicing
x[5:9]: [5 6 7 8]
x[:5]: [0 1 2 3 4]
x[1::3]: [1 4 7]
x2[0:2, 0:2]:
 [[1 2]
 [4 5]]


In [6]:
# Concatenation of arrays
print("\nConcatenation of arrays")
p = np.array([1, 2, 3])
q = np.array([8, 12, 14])
print("Concatenated array:", np.concatenate([p, q]))


Concatenation of arrays
Concatenated array: [ 1  2  3  8 12 14]


In [7]:
# Splitting of array
print("\nSplitting of array")
y = np.array([1, 2, 3, 99, 99, 3, 2, 1])
d, e = np.split(x, [2])
print("Split arrays:", d, e)


Splitting of array
Split arrays: [0 1] [2 3 4 5 6 7 8 9]


In [8]:
# Functions
print("\nFunctions")
t = np.array([1, 2, 3])
print("Add:", np.add(t, 2))
print("Subtract:", np.subtract(t, 2))
print("Negative:", np.negative(t))
print("Multiply:", np.multiply(t, 2))
print("Divide:", np.divide(t, 5))
print("Floor divide:", np.floor_divide(t, 2))
print("Power:", np.power(t, 2))
print("Modulus:", np.mod(t, 2))


Functions
Add: [3 4 5]
Subtract: [-1  0  1]
Negative: [-1 -2 -3]
Multiply: [2 4 6]
Divide: [0.2 0.4 0.6]
Floor divide: [0 1 1]
Power: [1 4 9]
Modulus: [1 0 1]


In [9]:
# Absolute
print("\nAbsolute function")
print("Absolute:", np.absolute([-1, -2, 0, 1, 2]))

# Trigonometric functions
print("\nTrigonometric functions")
theta = np.array([0, 1.57, 3.14])
print("Sin:", np.sin(theta))
print("Cos:", np.cos(theta))
print("Tan:", np.tan(theta))


Absolute function
Absolute: [1 2 0 1 2]

Trigonometric functions
Sin: [0.         0.99999968 0.00159265]
Cos: [ 1.00000000e+00  7.96326711e-04 -9.99998732e-01]
Tan: [ 0.00000000e+00  1.25576559e+03 -1.59265494e-03]


In [10]:
# Exponential functions
print("\nExponential functions")
print("Exp:", np.exp(x))
print("Exp2:", np.exp2(x))
print("Power (x^3):", np.power(x, 3))


Exponential functions
Exp: [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
Exp2: [  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
Power (x^3): [  0   1   8  27  64 125 216 343 512 729]


In [11]:
# Logarithmic functions
print("\nLogarithmic functions")
o = np.array([1, 10, 100])
print("Log:", np.log(o))
print("Log2:", np.log2(o))
print("Log10:", np.log10(o))


Logarithmic functions
Log: [0.         2.30258509 4.60517019]
Log2: [0.         3.32192809 6.64385619]
Log10: [0. 1. 2.]
