In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
print (" OUTPUT IS ")
print("ONE DIMENSIONAL ARRAY IS:\n",a)
b=np.array([[10,20],[40,50]])
print (" TWO DIMENSIONAL ARRAY IS:\n",b)
c=np.array([[10,20,30],[40,50,60],[70,80,90]])
print (" THREE DIMENSIONAL ARRAY IS:\n", c)


 OUTPUT IS 
ONE DIMENSIONAL ARRAY IS:
 [ 1  2  3  4  5  6  7  8  9 10]
 TWO DIMENSIONAL ARRAY IS:
 [[10 20]
 [40 50]]
 THREE DIMENSIONAL ARRAY IS:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [4]:
# Array indexing and numpy array atributes
x1 = np.array([45,89,64,33])
x2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array indexing and numpy array atributes")
print(x1)
print("x2 ndim:",x2.ndim)
print("x2 shape:",x2.shape)
print("x2 size:",x2.size)


Array indexing and numpy array atributes
[45 89 64 33]
x2 ndim: 2
x2 shape: (3, 3)
x2 size: 9


In [5]:
# Accessing single elements
print("accessing single elements")
print(x1[-2])
print(x2)
x2[1,2] = 60
print(x2)
# Array slicing
print("array slicing")
x = np.arange(10)
print(x[5:9])
print(x[:5])
print(x[1::3])
print(x2)
print(x2[0:2,0:2])


accessing single elements
64
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5 60]
 [ 7  8  9]]
array slicing
[5 6 7 8]
[0 1 2 3 4]
[1 4 7]
[[ 1  2  3]
 [ 4  5 60]
 [ 7  8  9]]
[[1 2]
 [4 5]]


In [6]:
# Concatenation of arrays
print("concatenation of arrays")
p = np.array([1,2,3])
q = np.array([8,12,14])
print(np.concatenate([p,q]))

# Splitting of array
print("splitting of array")
y = [1,2,3,99,99,3,2,1]
d,e = np.split(x,[2])
print(d,e)

# Functions
print("Function:")
print("add")
t = np.array([1,2,3])
print(np.add(t,2))
print("Subtract")
print(np.subtract(t,2))
print("negative")
print(np.negative(t))
print("multiply")
print(np.multiply(t,2))
print("divide")
print(np.divide(t,5))
print("floor divide")
print(np.floor_divide(t,2))
print("power")
print(np.power(t,2))
print("modulus")
print(np.mod(t,2))

# Absolute
print("Absolute")
print(np.absolute([-1,-2,0,1,2]))

# Trigonometric
print("trignometric")
theta = [0,1.57,3.14]
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

# Exponent
print("Exponent")
print(np.exp(x))
print(np.exp2(x))
print(np.power(x,3))
print("Log")
o = [1,10,100]
print(np.log(o))
print(np.log2(o))
print(np.log10(o))


concatenation of arrays
[ 1  2  3  8 12 14]
splitting of array
[0 1] [2 3 4 5 6 7 8 9]
Function:
add
[3 4 5]
Subtract
[-1  0  1]
negative
[-1 -2 -3]
multiply
[2 4 6]
divide
[0.2 0.4 0.6]
floor divide
[0 1 1]
power
[1 4 9]
modulus
[1 0 1]
Absolute
[1 2 0 1 2]
trignometric
[0.         0.99999968 0.00159265]
[ 1.00000000e+00  7.96326711e-04 -9.99998732e-01]
[ 0.00000000e+00  1.25576559e+03 -1.59265494e-03]
Exponent
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
[  0   1   8  27  64 125 216 343 512 729]
Log
[0.         2.30258509 4.60517019]
[0.         3.32192809 6.64385619]
[0. 1. 2.]
